Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [1]:
import numpy as np

# n is the number of columns in the output matrix
# when increasing is False, the i-th output column is the input vector raised element-wise to the power of n - i - 1
# when increasing is True, the i-th output column is the input vector raised element-wise to the power of i

def vander_matrix(invector, n=None, increasing=False):

    if n is None:
        n = len(invector)
    if not increasing:
        result = np.column_stack([invector**(n-1-i) for i in range(n)])
    elif increasing:
        result = np.column_stack([invector**i for i in range(n)])
    
    return result

In [2]:
x = np.array([1,2,3,4,5])
vander_matrix(x)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]], dtype=int32)

In [3]:
vander_matrix(x, increasing=True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]], dtype=int32)

In [4]:
vander_matrix(x, 3)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]], dtype=int32)

In [5]:
vander_matrix(x, 3, True)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25]], dtype=int32)

# Problem Statement

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i     1  2  3  4  5  6  7  8  9  10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 :   25 = (10+20+30+40)/4

y2 :   35 = (20+30+40+50)/4

y3 :   45 = (30+40+50+60)/4

y4 :   55 = (40+50+60+70)/4

y5 :   65 = (50+60+70+80)/4

y6 :   75 = (60+70+80+90)/4

y7 :   85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

# Question:
    
Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [6]:
def mov_avg(inseq, k):
    """For the input sequence return the moving average sequence"""
    if k <= 0:
        raise ValueError("Window size must be greater than zero")
    return np.array([sum(inseq[i:(i+k)])/k for i in range(len(inseq)-k+1)])

In [7]:
mov_avg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150], 3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])